### ISSUE TITLE
프로젝트 탭을 생성했어요.

### ISSUE THREAD

**Issue by khw7096** [lazypic/Sewol#1]
https://github.com/orgs/lazypic/projects/30

구상, 필요파트, 도움요청등을 적으면 좋아요. 블랜더 아티스트를 위해서 abc 파일을 공유하면 좋아요!

**Comment by khw7096** [comment]
일단 생성을 완료했으니 이 이슈는 닫습니다.

**Comment by sangery8** [comment]
선체 모델은 어디서 받으면 될까요?

**Comment by khw7096** [comment]
이건 다른 이슈이니... 따로 이슈를 만들께요.
