### ISSUE TITLE
선체 모델은 어디서 받으면 될까요? -sangery8

### ISSUE THREAD

**Issue by khw7096** [lazypic/Sewol#3]

**Comment by khw7096** [comment]
용량이 작다면 github를 사용하고,

용량이 크다면 aws지원할께요.
(작업인원에 대해서 프로젝트 계정이 발급될꺼예료.)

**Comment by sehwanjo10** [comment]
[데이터구성]
-모델링 데이터 : MB파일 1개
- 텍스쳐 : Top, Side, Bottom 에 대한 8192 x 8192 사이즈 3장

총 용량 : 227mb

**Comment by khw7096** [comment]
github로 올려도 되겠네요.

**Comment by sehwanjo10** [comment]
abc 모델링 데이터가 120mb 인데

'Yowza, that’s a big file. Try again with a file smaller than 25MB'

라며 업로드가 안되네요 ㅜ

**Comment by khw7096** [comment]
그럼 AWS로~~!!

**Comment by khw7096** [comment]
데이터가 올라가면 알려주세요. 이 이슈를 닫을께요~!

**Comment by khw7096** [comment]
다운받을수 있는 계정이 발급되어서 이 이슈를 닫습니다.
