### ISSUE TITLE
Readme 에 표기한 작업기한보다 조금 더 늘리는건 어떤가요?

### ISSUE THREAD

**Issue by khw7096** [lazypic/Sewol#6]
오픈프로젝트가 될 수 있어서.. 미리 여쭈어 봅니다.

**Comment by sehwanjo10** [comment]
대중에게 공개되어지는 날이 세월호 5주기인 2019.04.16 로 생각하고 있었는데 혹시 이부분에 대해서 의견 여쭈어 보아요~

**Comment by khw7096** [comment]
날짜가 의미가 있네요.

**Comment by khw7096** [comment]
일단 이슈가 생길 때 다시 reopen 할께요.
