### ISSUE TITLE
AWS에 선체 데이터 업로드 및 데이터 체크 (진행중)

### ISSUE THREAD

**Issue by sehwanjo10** [lazypic/sewol#8]

**Comment by khw7096** [comment]
done

**Comment by sangery8** [comment]
sangery@naver.com

**Comment by khw7096** [comment]
메일 보내드렸어요~!

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/54831209-4a63c480-4cfd-11e9-84a1-2598da9245ad.png)

abc 파일에 UV가 없어용.

**Comment by khw7096** [comment]
s3://sewol.lazypic.org/assets/sewol.blend 파일을 올렸어요.

이 파일 하나만 받으면 일단 모델링, 이미지는 내장되어 있어요. UV가 있는 abc를 받으면 교체해보죠~!

**Comment by sangery8** [comment]
제가 아직 깃허브 시스템을 잘 몰라서.. 어떻게 접근하지를 모르겠어요.. aws 계정은 생성했는데..  어디서 데이터를 받아야하는지 모르겠네요 ㅠㅠ

**Comment by khw7096** [comment]
상단에 Services 라는 항목에서 S3를 먼저 찾아보세요!

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/54858651-71e07e80-4d49-11e9-99ac-26ef1d1ac6a2.png)


항목이 보일꺼예요.. 어짜피 나머지 디렉토리는 들어갈 수 없어요~!

**Comment by sehwanjo10** [comment]
앗 UV 가 없이 빠졌나보군요!  체크해보고 업데이트 후에 코멘트 달게요~!

**Comment by sehwanjo10** [comment]
선체 데이터 UV 포함 확인 후 AWS에 업로드 완료하였어요~!

**Comment by khw7096** [comment]
Thank you for your time and effort. I really appreciate it.

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/54915816-60f75f00-4f3b-11e9-9dac-4d1abc9d473a.png)

데이터 체크 완료. 다 되면... 에셋에는 blender 파일만 남기고 삭제할께요.

**Comment by khw7096** [comment]
![image](https://user-images.githubusercontent.com/1149996/54916941-fbf13880-4f3d-11e9-8732-b83b96490084.png)

텍스쳐가 포함된 블랜더 파일 하나만 남겼어요.

**Comment by khw7096** [comment]
데이터가 정상적으로 올라갔습니다. 이 이슈는 닫습니다.
