### ISSUE TITLE
이 리포지터리의 이름을 소문자로 바꾸는 건 어때요?

### ISSUE THREAD

**Issue by khw7096** [lazypic/sewol#9]
- 클라우드 / aws : s3://sewol.lazypic.org
- 로컬환경 / localdrive : ~/project/sewol/..
- 코드이슈 / github : https://github.com/lazypic/sewol
- 협업환경 / slack chennel : #sewol
- 메일알리아스 / sewol@lazypic.org

5개의 경로를 통일하면 굉장히 편할 것 같아요. 추후 이 부분을 자동화 하기도 편리하구요!

**Comment by sehwanjo10** [comment]
네!!

**Comment by sehwanjo10** [comment]
수정 완료하였습니다.~!

**Comment by khw7096** [comment]
The issue is resolved and this issue is closed.
